<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>ProxyPython</name>
    <message>
        <location filename="proxy/proxypython.cpp" line="170"/>
        <source>The path to Mod Organizer (%1) contains a semicolon.&lt;br&gt;While this is legal on NTFS drives, many applications do not handle it correctly.&lt;br&gt;Unfortunately MO depends on libraries that seem to fall into that group.&lt;br&gt;As a result the python plugin cannot be loaded, and the only solution we can offer is to remove the semicolon or move MO to a path without a semicolon.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="180"/>
        <source>The Python plugin DLL was not found, maybe your antivirus deleted it. Re-installing MO2 might fix the problem.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="183"/>
        <source>The Python plugin DLL is invalid, maybe your antivirus is blocking it. Re-installing MO2 and adding exclusions for it to your AV might fix the problem.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="188"/>
        <source>The initialization of the Python plugin DLL failed, unfortunately without any details.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="191"/>
        <source>no failure</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="runner/error.h" line="76"/>
        <source>An unknown exception was thrown in python code.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
